const data = {
  products: [
    {
      id: "1",
      name: "Nike Slim Shirt",
      category: "Slim Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 1.5,
      numReviews: 10,
      Description: "High quality prodcuts",
    },
    {
      id: "2",
      name: "Adidas Slim Shirt",
      category: "Slim Shirts",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 12,
      brand: "Adida",
      rating: 2.0,
      numReviews: 10,
      Description: "High quality prodcuts",
    },
    {
      id: "3",
      name: "Lacoste Free Shirt",
      category: "Free Shirts",
      image: "/images/p3.jpg",
      price: 130,
      countInStock: 1,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      Description: "High quality prodcuts",
    },
    {
      id: "4",
      name: "Nike T-Shirt",
      category: "T-Shirts",
      image: "/images/p4.jpg",
      price: 150,
      countInStock: 33,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      Description: "High quality prodcuts",
    },
    {
      id: "5",
      name: "Puma Shirt",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 112,
      countInStock: 1,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      Description: "High quality prodcuts",
    },
    {
      id: "6",
      name: "Adidas Fit Pant",
      category: "Fit Pants",
      image: "/images/p6.jpg",
      price: 120,
      countInStock: 0,
      brand: "Adidas",
      rating: 4,
      numReviews: 10,
      Description: "High quality prodcuts",
    },
  ],
};
export default data;
